version: "3.7"
services:
  redis:
    image: "redis:5.0.5"
    volumes:
      - "./data:/data"
  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    entrypoint:
      - server
      - -v
    depends_on:
      - redis
