version: "3.7"
services:
  server:
    image: selfpass:latest
    restart: on-failure
    entrypoint:
      - server
      - -v
    ports:
      - "8080:8080"
    volumes:
      - "./data:/home/selfpass/data"
    secrets:
      - ca
      - cert
      - key
secrets:
  ca:
    file: "./certs/ca.pem"
  cert:
    file: "./certs/server.pem"
  key:
    file: "./certs/server-key.pem"
