version: "3.7"
services:
  server:
    image: mjfs/selfpass:latest
    ports:
      - "8080:8080"
    volumes:
      - data:/home/selfpass/data
    secrets:
      - ca
      - cert
      - key
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  ca:
    file: ./certs/ca.pem
  cert:
    file: ./certs/server.pem
  key:
    file: ./certs/server-key.pem

volumes:
  data:
    driver: local
    driver_opts:
      type: "ext4"
      device: "/dev/sdb1"
