version: "3.7"
services:
  redis:
    image: "redis:5.0.5"
    restart: on-failure
    command:
      - redis-server
      - /redis.conf
    volumes:
      - "./redis.conf:/redis.conf"
      - "./data:/data"
  server:
    build: .
    restart: on-failure
    entrypoint:
      - server
      - -v
    ports:
      - "8080:8080"
    depends_on:
      - redis
