#!/usr/bin/env sh
ca=$(cat ./certs/ca.pem)
cert=$(cat ./certs/server.pem)
key=$(cat ./certs/server-key.pem)

cat << EOM
// Code generated by gen_certs_go.sh, DO NOT EDIT.
package main

const ca = \`${ca}\`
const cert = \`${cert}\`
const key = \`${key}\`
EOM
