// Code generated by protoc-gen-go. DO NOT EDIT.
// source: credentials.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SuccessResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuccessResponse) Reset()         { *m = SuccessResponse{} }
func (m *SuccessResponse) String() string { return proto.CompactTextString(m) }
func (*SuccessResponse) ProtoMessage()    {}
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f10b41ff9e8e07a, []int{0}
}

func (m *SuccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuccessResponse.Unmarshal(m, b)
}
func (m *SuccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuccessResponse.Marshal(b, m, deterministic)
}
func (m *SuccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuccessResponse.Merge(m, src)
}
func (m *SuccessResponse) XXX_Size() int {
	return xxx_messageInfo_SuccessResponse.Size(m)
}
func (m *SuccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SuccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SuccessResponse proto.InternalMessageInfo

func (m *SuccessResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SourceHostRequest struct {
	SourceHost           string   `protobuf:"bytes,1,opt,name=source_host,json=sourceHost,proto3" json:"source_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceHostRequest) Reset()         { *m = SourceHostRequest{} }
func (m *SourceHostRequest) String() string { return proto.CompactTextString(m) }
func (*SourceHostRequest) ProtoMessage()    {}
func (*SourceHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f10b41ff9e8e07a, []int{1}
}

func (m *SourceHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceHostRequest.Unmarshal(m, b)
}
func (m *SourceHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceHostRequest.Marshal(b, m, deterministic)
}
func (m *SourceHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceHostRequest.Merge(m, src)
}
func (m *SourceHostRequest) XXX_Size() int {
	return xxx_messageInfo_SourceHostRequest.Size(m)
}
func (m *SourceHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SourceHostRequest proto.InternalMessageInfo

func (m *SourceHostRequest) GetSourceHost() string {
	if m != nil {
		return m.SourceHost
	}
	return ""
}

type IdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f10b41ff9e8e07a, []int{2}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateRequest struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Credential           *CredentialRequest `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f10b41ff9e8e07a, []int{3}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetCredential() *CredentialRequest {
	if m != nil {
		return m.Credential
	}
	return nil
}

type Metadata struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Primary              string               `protobuf:"bytes,4,opt,name=primary,proto3" json:"primary,omitempty"`
	SourceHost           string               `protobuf:"bytes,5,opt,name=source_host,json=sourceHost,proto3" json:"source_host,omitempty"`
	LoginUrl             string               `protobuf:"bytes,6,opt,name=login_url,json=loginUrl,proto3" json:"login_url,omitempty"`
	Tag                  string               `protobuf:"bytes,7,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f10b41ff9e8e07a, []int{4}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Metadata) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Metadata) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Metadata) GetPrimary() string {
	if m != nil {
		return m.Primary
	}
	return ""
}

func (m *Metadata) GetSourceHost() string {
	if m != nil {
		return m.SourceHost
	}
	return ""
}

func (m *Metadata) GetLoginUrl() string {
	if m != nil {
		return m.LoginUrl
	}
	return ""
}

func (m *Metadata) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type Credential struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Primary              string               `protobuf:"bytes,4,opt,name=primary,proto3" json:"primary,omitempty"`
	Username             string               `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Email                string               `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	SourceHost           string               `protobuf:"bytes,8,opt,name=source_host,json=sourceHost,proto3" json:"source_host,omitempty"`
	LoginUrl             string               `protobuf:"bytes,9,opt,name=login_url,json=loginUrl,proto3" json:"login_url,omitempty"`
	Tag                  string               `protobuf:"bytes,10,opt,name=tag,proto3" json:"tag,omitempty"`
	OtpSecret            string               `protobuf:"bytes,11,opt,name=otp_secret,json=otpSecret,proto3" json:"otp_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Credential) Reset()         { *m = Credential{} }
func (m *Credential) String() string { return proto.CompactTextString(m) }
func (*Credential) ProtoMessage()    {}
func (*Credential) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f10b41ff9e8e07a, []int{5}
}

func (m *Credential) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credential.Unmarshal(m, b)
}
func (m *Credential) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credential.Marshal(b, m, deterministic)
}
func (m *Credential) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credential.Merge(m, src)
}
func (m *Credential) XXX_Size() int {
	return xxx_messageInfo_Credential.Size(m)
}
func (m *Credential) XXX_DiscardUnknown() {
	xxx_messageInfo_Credential.DiscardUnknown(m)
}

var xxx_messageInfo_Credential proto.InternalMessageInfo

func (m *Credential) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Credential) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Credential) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Credential) GetPrimary() string {
	if m != nil {
		return m.Primary
	}
	return ""
}

func (m *Credential) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credential) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Credential) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Credential) GetSourceHost() string {
	if m != nil {
		return m.SourceHost
	}
	return ""
}

func (m *Credential) GetLoginUrl() string {
	if m != nil {
		return m.LoginUrl
	}
	return ""
}

func (m *Credential) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Credential) GetOtpSecret() string {
	if m != nil {
		return m.OtpSecret
	}
	return ""
}

type CredentialRequest struct {
	Primary              string   `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	SourceHost           string   `protobuf:"bytes,5,opt,name=source_host,json=sourceHost,proto3" json:"source_host,omitempty"`
	LoginUrl             string   `protobuf:"bytes,6,opt,name=login_url,json=loginUrl,proto3" json:"login_url,omitempty"`
	Tag                  string   `protobuf:"bytes,7,opt,name=tag,proto3" json:"tag,omitempty"`
	OtpSecret            string   `protobuf:"bytes,8,opt,name=otp_secret,json=otpSecret,proto3" json:"otp_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CredentialRequest) Reset()         { *m = CredentialRequest{} }
func (m *CredentialRequest) String() string { return proto.CompactTextString(m) }
func (*CredentialRequest) ProtoMessage()    {}
func (*CredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f10b41ff9e8e07a, []int{6}
}

func (m *CredentialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CredentialRequest.Unmarshal(m, b)
}
func (m *CredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CredentialRequest.Marshal(b, m, deterministic)
}
func (m *CredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CredentialRequest.Merge(m, src)
}
func (m *CredentialRequest) XXX_Size() int {
	return xxx_messageInfo_CredentialRequest.Size(m)
}
func (m *CredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CredentialRequest proto.InternalMessageInfo

func (m *CredentialRequest) GetPrimary() string {
	if m != nil {
		return m.Primary
	}
	return ""
}

func (m *CredentialRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CredentialRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CredentialRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CredentialRequest) GetSourceHost() string {
	if m != nil {
		return m.SourceHost
	}
	return ""
}

func (m *CredentialRequest) GetLoginUrl() string {
	if m != nil {
		return m.LoginUrl
	}
	return ""
}

func (m *CredentialRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *CredentialRequest) GetOtpSecret() string {
	if m != nil {
		return m.OtpSecret
	}
	return ""
}

func init() {
	proto.RegisterType((*SuccessResponse)(nil), "selfpass.SuccessResponse")
	proto.RegisterType((*SourceHostRequest)(nil), "selfpass.SourceHostRequest")
	proto.RegisterType((*IdRequest)(nil), "selfpass.IdRequest")
	proto.RegisterType((*UpdateRequest)(nil), "selfpass.UpdateRequest")
	proto.RegisterType((*Metadata)(nil), "selfpass.Metadata")
	proto.RegisterType((*Credential)(nil), "selfpass.Credential")
	proto.RegisterType((*CredentialRequest)(nil), "selfpass.CredentialRequest")
}

func init() { proto.RegisterFile("credentials.proto", fileDescriptor_9f10b41ff9e8e07a) }

var fileDescriptor_9f10b41ff9e8e07a = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x9d, 0x36, 0xb5, 0x27, 0xa2, 0x90, 0xa5, 0x12, 0xc6, 0x11, 0x6a, 0xe5, 0x53, 0x25,
	0x24, 0xb7, 0x2a, 0x48, 0x80, 0x7a, 0x0a, 0x41, 0x2a, 0x1c, 0xb8, 0x38, 0xf4, 0x82, 0x90, 0xa2,
	0xad, 0x3d, 0x0d, 0x96, 0xec, 0xac, 0xd9, 0x1d, 0x0b, 0xf1, 0xbf, 0xf8, 0x53, 0xf0, 0x13, 0x38,
	0x21, 0xaf, 0xbf, 0x52, 0x27, 0x0e, 0x07, 0x2e, 0xbd, 0xed, 0xcc, 0xbc, 0x37, 0xda, 0xf7, 0x34,
	0x33, 0x30, 0x0e, 0x25, 0x46, 0xb8, 0xa2, 0x98, 0x27, 0xca, 0xcf, 0xa4, 0x20, 0xc1, 0x2c, 0x85,
	0xc9, 0x6d, 0xc6, 0x95, 0x72, 0x8f, 0x97, 0x42, 0x2c, 0x13, 0x3c, 0xd3, 0xf9, 0x9b, 0xfc, 0xf6,
	0x8c, 0xe2, 0x14, 0x15, 0xf1, 0x34, 0x2b, 0xa1, 0xde, 0x73, 0x78, 0x38, 0xcf, 0xc3, 0x10, 0x95,
	0x0a, 0x50, 0x65, 0x62, 0xa5, 0x90, 0x39, 0x70, 0xa0, 0xca, 0x94, 0x63, 0x9c, 0x18, 0xa7, 0x56,
	0x50, 0x87, 0xde, 0x4b, 0x18, 0xcf, 0x45, 0x2e, 0x43, 0x7c, 0x2f, 0x14, 0x05, 0xf8, 0x2d, 0x47,
	0x45, 0xec, 0x18, 0x46, 0x4a, 0x27, 0x17, 0x5f, 0x85, 0x22, 0x4d, 0xb1, 0x03, 0x50, 0x0d, 0xce,
	0x9b, 0x80, 0xfd, 0x21, 0xaa, 0xd1, 0x87, 0x60, 0xc6, 0x51, 0x05, 0x32, 0xe3, 0xc8, 0xfb, 0x02,
	0x0f, 0xae, 0xb3, 0x88, 0x13, 0xf6, 0x00, 0xd8, 0x25, 0x40, 0x2b, 0xd0, 0x31, 0x4f, 0x8c, 0xd3,
	0xd1, 0xc5, 0xc4, 0xaf, 0x05, 0xfa, 0xb3, 0xa6, 0x56, 0x35, 0x08, 0xd6, 0xe0, 0xde, 0x1f, 0x03,
	0xac, 0x8f, 0x48, 0x3c, 0xe2, 0xc4, 0x37, 0x3a, 0xbf, 0xd1, 0x9d, 0x39, 0x61, 0xb4, 0xe0, 0x54,
	0x75, 0x76, 0xfd, 0xd2, 0x30, 0xbf, 0x36, 0xcc, 0xff, 0x54, 0x1b, 0x16, 0xd8, 0x15, 0x7a, 0x4a,
	0x05, 0x35, 0xd7, 0xbf, 0xd6, 0xd4, 0xc1, 0xbf, 0xa9, 0x15, 0x7a, 0x4a, 0x85, 0xbb, 0x99, 0x8c,
	0x53, 0x2e, 0x7f, 0x38, 0x7b, 0xfa, 0x2b, 0x75, 0xd8, 0x35, 0x72, 0xbf, 0x6b, 0x24, 0x9b, 0x80,
	0x9d, 0x88, 0x65, 0xbc, 0x5a, 0xe4, 0x32, 0x71, 0x86, 0xba, 0x6c, 0xe9, 0xc4, 0xb5, 0x4c, 0xd8,
	0x23, 0x18, 0x10, 0x5f, 0x3a, 0x07, 0x3a, 0x5d, 0x3c, 0xbd, 0x5f, 0x26, 0x40, 0x6b, 0xcf, 0xbd,
	0x97, 0xef, 0x82, 0x95, 0x2b, 0x94, 0x2b, 0x9e, 0x62, 0xa5, 0xbd, 0x89, 0xd9, 0x11, 0xec, 0x63,
	0xca, 0xe3, 0x5a, 0x75, 0x19, 0x14, 0x8c, 0x62, 0x06, 0xbe, 0x0b, 0x19, 0x55, 0xba, 0x9b, 0xb8,
	0x6b, 0xa6, 0xb5, 0xdb, 0x4c, 0x7b, 0xbb, 0x99, 0xd0, 0x98, 0xc9, 0x9e, 0x01, 0x08, 0xca, 0x16,
	0x0a, 0x43, 0x89, 0xe4, 0x8c, 0x74, 0xc1, 0x16, 0x94, 0xcd, 0x75, 0xc2, 0xfb, 0x6d, 0xc0, 0x78,
	0x63, 0x14, 0xd7, 0xc5, 0x1a, 0xfd, 0x62, 0xcd, 0x3e, 0xb1, 0x83, 0x3e, 0xb1, 0x7b, 0xbb, 0xc5,
	0xfe, 0xef, 0xe4, 0x74, 0xc4, 0x5a, 0x1d, 0xb1, 0x17, 0x3f, 0x4d, 0x18, 0xb5, 0x62, 0x15, 0x9b,
	0xc1, 0xe1, 0x15, 0xd2, 0x34, 0x49, 0x9a, 0x55, 0x5b, 0x5b, 0xd0, 0x8d, 0x83, 0xe1, 0xb2, 0xb6,
	0x58, 0x13, 0xce, 0x0d, 0x76, 0x0e, 0x83, 0x2b, 0x24, 0xf6, 0xb8, 0x2d, 0x36, 0x47, 0xc3, 0x3d,
	0xda, 0xb6, 0xef, 0xec, 0x12, 0x86, 0x33, 0x3d, 0x92, 0x6c, 0xd7, 0x3d, 0xe8, 0x21, 0xbf, 0x82,
	0x61, 0x79, 0x77, 0xd8, 0x93, 0xb6, 0x7e, 0xe7, 0x12, 0xf5, 0x10, 0x5f, 0xc3, 0xf0, 0x1d, 0x26,
	0x48, 0xb8, 0xfd, 0xab, 0x4f, 0xd7, 0x94, 0xdf, 0xbd, 0xab, 0x6f, 0xe1, 0xb3, 0x55, 0xef, 0xc6,
	0xcd, 0x50, 0xbf, 0x5e, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x06, 0xb4, 0x9b, 0xbe, 0xbd, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CredentialsClient is the client API for Credentials service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CredentialsClient interface {
	GetAllMetadata(ctx context.Context, in *SourceHostRequest, opts ...grpc.CallOption) (Credentials_GetAllMetadataClient, error)
	Get(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Credential, error)
	Create(ctx context.Context, in *CredentialRequest, opts ...grpc.CallOption) (*Credential, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Credential, error)
	Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SuccessResponse, error)
}

type credentialsClient struct {
	cc *grpc.ClientConn
}

func NewCredentialsClient(cc *grpc.ClientConn) CredentialsClient {
	return &credentialsClient{cc}
}

func (c *credentialsClient) GetAllMetadata(ctx context.Context, in *SourceHostRequest, opts ...grpc.CallOption) (Credentials_GetAllMetadataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Credentials_serviceDesc.Streams[0], "/selfpass.Credentials/GetAllMetadata", opts...)
	if err != nil {
		return nil, err
	}
	x := &credentialsGetAllMetadataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Credentials_GetAllMetadataClient interface {
	Recv() (*Metadata, error)
	grpc.ClientStream
}

type credentialsGetAllMetadataClient struct {
	grpc.ClientStream
}

func (x *credentialsGetAllMetadataClient) Recv() (*Metadata, error) {
	m := new(Metadata)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *credentialsClient) Get(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Credential, error) {
	out := new(Credential)
	err := c.cc.Invoke(ctx, "/selfpass.Credentials/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsClient) Create(ctx context.Context, in *CredentialRequest, opts ...grpc.CallOption) (*Credential, error) {
	out := new(Credential)
	err := c.cc.Invoke(ctx, "/selfpass.Credentials/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Credential, error) {
	out := new(Credential)
	err := c.cc.Invoke(ctx, "/selfpass.Credentials/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *credentialsClient) Delete(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/selfpass.Credentials/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CredentialsServer is the server API for Credentials service.
type CredentialsServer interface {
	GetAllMetadata(*SourceHostRequest, Credentials_GetAllMetadataServer) error
	Get(context.Context, *IdRequest) (*Credential, error)
	Create(context.Context, *CredentialRequest) (*Credential, error)
	Update(context.Context, *UpdateRequest) (*Credential, error)
	Delete(context.Context, *IdRequest) (*SuccessResponse, error)
}

// UnimplementedCredentialsServer can be embedded to have forward compatible implementations.
type UnimplementedCredentialsServer struct {
}

func (*UnimplementedCredentialsServer) GetAllMetadata(req *SourceHostRequest, srv Credentials_GetAllMetadataServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllMetadata not implemented")
}
func (*UnimplementedCredentialsServer) Get(ctx context.Context, req *IdRequest) (*Credential, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedCredentialsServer) Create(ctx context.Context, req *CredentialRequest) (*Credential, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedCredentialsServer) Update(ctx context.Context, req *UpdateRequest) (*Credential, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedCredentialsServer) Delete(ctx context.Context, req *IdRequest) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterCredentialsServer(s *grpc.Server, srv CredentialsServer) {
	s.RegisterService(&_Credentials_serviceDesc, srv)
}

func _Credentials_GetAllMetadata_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SourceHostRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CredentialsServer).GetAllMetadata(m, &credentialsGetAllMetadataServer{stream})
}

type Credentials_GetAllMetadataServer interface {
	Send(*Metadata) error
	grpc.ServerStream
}

type credentialsGetAllMetadataServer struct {
	grpc.ServerStream
}

func (x *credentialsGetAllMetadataServer) Send(m *Metadata) error {
	return x.ServerStream.SendMsg(m)
}

func _Credentials_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selfpass.Credentials/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServer).Get(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Credentials_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selfpass.Credentials/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServer).Create(ctx, req.(*CredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Credentials_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selfpass.Credentials/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Credentials_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selfpass.Credentials/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServer).Delete(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Credentials_serviceDesc = grpc.ServiceDesc{
	ServiceName: "selfpass.Credentials",
	HandlerType: (*CredentialsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Credentials_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Credentials_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Credentials_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Credentials_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllMetadata",
			Handler:       _Credentials_GetAllMetadata_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "credentials.proto",
}
